import type { ToolCatalogEntry } from "./types.js";

export const networkTools: ToolCatalogEntry[] = [
  { id: "autorecon", displayName: "AutoRecon", binary: "autorecon", category: "network", riskTier: "passive", phase: "recon", osiLayers: ["L3", "L4", "L7"], tags: ["network", "recon", "service-enum"] },
  { id: "masscan", displayName: "Masscan", binary: "masscan", category: "network", riskTier: "active", phase: "recon", osiLayers: ["L3", "L4"], tags: ["network", "port-scan", "high-speed"] },
  { id: "ncat", displayName: "Ncat", binary: "ncat", category: "network", riskTier: "passive", phase: "enum", osiLayers: ["L4", "L7"], tags: ["network", "tcp", "banner-grab", "probe"] },
  { id: "netcat", displayName: "Netcat", binary: "nc", category: "network", riskTier: "passive", phase: "enum", osiLayers: ["L4", "L7"], tags: ["network", "tcp", "banner-grab", "probe"] },
  { id: "nmap", displayName: "Nmap", binary: "nmap", category: "network", riskTier: "passive", notes: "Implemented via network_scan/service_scan.", phase: "enum", osiLayers: ["L3", "L4", "L7"], tags: ["network", "port-scan", "service-enum"] },
  { id: "rustscan", displayName: "RustScan", binary: "rustscan", category: "network", riskTier: "passive", phase: "recon", osiLayers: ["L3", "L4"], tags: ["network", "port-scan", "fast"] },
  { id: "network-segment-map", displayName: "Network Segment Map", binary: "nmap", category: "topology", riskTier: "passive", phase: "recon", osiLayers: ["L3", "L4"], tags: ["topology", "network", "recon", "lateral", "trust-boundary"] },
  { id: "service-fingerprint", displayName: "Service Fingerprint", binary: "nmap", category: "topology", riskTier: "passive", phase: "enum", osiLayers: ["L3", "L4", "L7"], tags: ["topology", "network", "service-enum", "cpe", "cve-correlation"] },
  { id: "tls-audit", displayName: "TLS Audit", binary: "openssl", category: "topology", riskTier: "passive", phase: "enum", osiLayers: ["L4", "L6"], tags: ["topology", "network", "tls", "ssl", "certificate", "trust-boundary"] },
  { id: "zmap", displayName: "ZMap", binary: "zmap", category: "network", riskTier: "active", phase: "recon", osiLayers: ["L3", "L4"], tags: ["network", "port-scan", "internet-scale"] },
  { id: "fping", displayName: "fping", binary: "fping", category: "network", riskTier: "passive", phase: "recon", osiLayers: ["L3"], tags: ["network", "ping", "host-discovery"] },
  { id: "hping3", displayName: "hping3", binary: "hping3", category: "network", riskTier: "active", phase: "recon", osiLayers: ["L3", "L4"], tags: ["network", "packet-craft", "firewall-test"] },
  { id: "angry-ip-scanner", displayName: "Angry IP Scanner", binary: "ipscan", category: "network", riskTier: "passive", phase: "recon", osiLayers: ["L3", "L4"], tags: ["network", "ip-scan", "host-discovery"] },
  { id: "asnmap", displayName: "ASNmap", binary: "asnmap", category: "network", riskTier: "passive", phase: "recon", osiLayers: ["L3"], tags: ["network", "asn", "cidr", "osint"] },
  { id: "nessus", displayName: "Nessus", binary: null, category: "network", riskTier: "active", notes: "Commercial scanner; requires Nessus server with web UI or API access.", phase: "vuln-scan", osiLayers: ["L3", "L4", "L7"], tags: ["network", "vuln-scan", "commercial"] },
  { id: "openvas", displayName: "OpenVAS", binary: "openvas", category: "network", riskTier: "active", phase: "vuln-scan", osiLayers: ["L3", "L4", "L7"], tags: ["network", "vuln-scan", "open-source"] },
  { id: "nexpose", displayName: "Nexpose", binary: null, category: "network", riskTier: "active", notes: "Commercial Rapid7 scanner; web UI or API access required.", phase: "vuln-scan", osiLayers: ["L3", "L4", "L7"], tags: ["network", "vuln-scan", "commercial"] },
  { id: "security-onion", displayName: "Security Onion", binary: null, category: "network", riskTier: "passive", notes: "Network security monitoring platform; not a standalone CLI tool.", phase: "utility", osiLayers: ["L3", "L4", "L7"], tags: ["network", "monitoring", "ids", "nsm"] },
  { id: "wireshark", displayName: "Wireshark", binary: "wireshark", category: "network", riskTier: "passive", phase: "enum", osiLayers: ["L2", "L3", "L4", "L7"], tags: ["network", "sniffer", "pcap", "traffic-analysis"] },
  { id: "tcpdump", displayName: "tcpdump", binary: "tcpdump", category: "network", riskTier: "passive", phase: "enum", osiLayers: ["L2", "L3", "L4", "L7"], tags: ["network", "sniffer", "pcap", "cli"] },
  { id: "netsniff-ng", displayName: "netsniff-ng", binary: "netsniff-ng", category: "network", riskTier: "passive", phase: "enum", osiLayers: ["L2", "L3", "L4", "L7"], tags: ["network", "sniffer", "pcap", "toolkit"] },
  { id: "debookee", displayName: "Debookee", binary: null, category: "network", riskTier: "passive", notes: "macOS GUI network analyzer; no CLI binary.", phase: "enum", osiLayers: ["L3", "L4", "L7"], tags: ["network", "sniffer", "macos", "traffic-analysis"] },
  { id: "dripcap", displayName: "Dripcap", binary: null, category: "network", riskTier: "passive", notes: "Electron-based GUI packet analyzer; no CLI binary.", phase: "enum", osiLayers: ["L2", "L3", "L4", "L7"], tags: ["network", "sniffer", "pcap", "gui"] },
  { id: "mitm6", displayName: "MITM6", binary: "mitm6", category: "network", riskTier: "controlled-exploit", phase: "exploit", osiLayers: ["L2", "L3"], tags: ["network", "ipv6", "mitm", "dhcpv6"] },
  { id: "ettercap", displayName: "Ettercap", binary: "ettercap", category: "network", riskTier: "controlled-exploit", phase: "exploit", osiLayers: ["L2", "L3", "L4", "L7"], tags: ["network", "mitm", "arp-poison", "sniffer"] },
  { id: "bettercap", displayName: "BetterCAP", binary: "bettercap", category: "network", riskTier: "active", phase: "exploit", osiLayers: ["L2", "L3", "L4", "L7"], tags: ["network", "mitm", "recon", "attack-framework"] },
  { id: "kismet", displayName: "Kismet", binary: "kismet", category: "network", riskTier: "passive", phase: "recon", osiLayers: ["L1", "L2"], tags: ["network", "wireless", "sniffer", "ids"] },
  { id: "unicornscan", displayName: "Unicornscan", binary: "unicornscan", category: "network", riskTier: "active", phase: "recon", osiLayers: ["L3", "L4"], tags: ["network", "port-scan", "async"] },
  { id: "scanless", displayName: "scanless", binary: "scanless", category: "network", riskTier: "passive", phase: "recon", osiLayers: ["L3", "L4"], tags: ["network", "port-scan", "anonymous", "proxy"] },
  { id: "xray", displayName: "XRay", binary: "xray", category: "network", riskTier: "active", phase: "recon", osiLayers: ["L3", "L4", "L7"], tags: ["network", "vuln-scan", "port-scan", "service-enum"] }
];
