import type { ToolCatalogEntry } from "./types.js";

export const webTools: ToolCatalogEntry[] = [
  { id: "arjun", displayName: "Arjun", binary: "arjun", category: "web", riskTier: "passive", phase: "enum", osiLayers: ["L7"], tags: ["web", "parameters", "discovery"] },
  { id: "burp-suite", displayName: "Burp Suite", binary: null, category: "web", riskTier: "active", notes: "Manual integration required.", phase: "enum", osiLayers: ["L7"], tags: ["web", "proxy", "manual"] },
  { id: "dalfox", displayName: "Dalfox", binary: "dalfox", category: "web", riskTier: "active", phase: "vuln-scan", osiLayers: ["L7"], tags: ["web", "xss", "fuzzing"] },
  { id: "httpx", displayName: "HTTPx", binary: "httpx", category: "web", riskTier: "passive", phase: "recon", osiLayers: ["L5", "L6", "L7"], tags: ["web", "http", "probe"] },
  { id: "nikto", displayName: "Nikto", binary: "nikto", category: "web", riskTier: "active", notes: "Implemented via nikto_scan.", phase: "vuln-scan", osiLayers: ["L7"], tags: ["web", "misconfig", "vuln-scan"] },
  { id: "nuclei", displayName: "Nuclei", binary: "nuclei", category: "web", riskTier: "active", notes: "Implemented via nuclei_scan.", phase: "vuln-scan", osiLayers: ["L7"], tags: ["web", "templates", "vuln-scan"] },
  { id: "paramspider", displayName: "ParamSpider", binary: "paramspider", category: "web", riskTier: "passive", phase: "enum", osiLayers: ["L7"], tags: ["web", "parameters", "archive"] },
  { id: "sqlmap", displayName: "SQLMap", binary: "sqlmap", category: "web", riskTier: "controlled-exploit", notes: "Implemented via db_injection_check.", phase: "exploit", osiLayers: ["L7"], tags: ["web", "sqli", "database"] },
  { id: "whatweb", displayName: "WhatWeb", binary: "whatweb", category: "web", riskTier: "passive", notes: "Implemented via web_fingerprint.", phase: "recon", osiLayers: ["L7"], tags: ["web", "fingerprint", "tech-stack"] },
  { id: "git-dumper", displayName: "git-dumper", binary: "git-dumper", category: "web", riskTier: "passive", phase: "recon", osiLayers: ["L7"], tags: ["web", "git", "source-code"] },
  { id: "eyewitness", displayName: "EyeWitness", binary: "EyeWitness", category: "web", riskTier: "passive", phase: "recon", osiLayers: ["L7"], tags: ["web", "screenshot", "fingerprint"] },
  { id: "wappalyzer", displayName: "Wappalyzer", binary: "wappalyzer", category: "web", riskTier: "passive", phase: "recon", osiLayers: ["L7"], tags: ["web", "fingerprint", "tech-stack"] },
  { id: "snallygaster", displayName: "snallygaster", binary: "snallygaster", category: "web", riskTier: "passive", phase: "recon", osiLayers: ["L7"], tags: ["web", "secrets", "exposed-files"] },
  { id: "parsero", displayName: "Parsero", binary: "parsero", category: "web", riskTier: "passive", phase: "recon", osiLayers: ["L7"], tags: ["web", "robots.txt", "osint"] },
  { id: "probely", displayName: "Probely", binary: null, category: "web", riskTier: "active", notes: "SaaS scanner; requires account and API key.", phase: "vuln-scan", osiLayers: ["L7"], tags: ["web", "vuln-scan", "saas", "dast"] },
  { id: "purpleteam", displayName: "purpleteam", binary: "purpleteam", category: "web", riskTier: "active", phase: "vuln-scan", osiLayers: ["L7"], tags: ["web", "vuln-scan", "regression", "owasp"] },
  { id: "panoptic", displayName: "Panoptic", binary: "panoptic", category: "web", riskTier: "active", phase: "vuln-scan", osiLayers: ["L7"], tags: ["web", "lfi", "path-traversal"] },
  { id: "grabber", displayName: "Grabber", binary: "grabber", category: "web", riskTier: "active", phase: "vuln-scan", osiLayers: ["L7"], tags: ["web", "vuln-scan", "xss", "sqli"] },
  { id: "w3af", displayName: "W3af", binary: "w3af", category: "web", riskTier: "active", phase: "vuln-scan", osiLayers: ["L7"], tags: ["web", "vuln-scan", "audit", "attack"] },
  { id: "wapiti", displayName: "Wapiti", binary: "wapiti", category: "web", riskTier: "active", phase: "vuln-scan", osiLayers: ["L7"], tags: ["web", "vuln-scan", "crawl"] },
  { id: "vega", displayName: "Vega", binary: null, category: "web", riskTier: "active", notes: "Java GUI scanner; no standard CLI binary.", phase: "vuln-scan", osiLayers: ["L7"], tags: ["web", "vuln-scan", "proxy"] },
  { id: "invicti", displayName: "Invicti (Netsparker)", binary: null, category: "web", riskTier: "active", notes: "Commercial scanner; requires Invicti subscription and web UI or API.", phase: "vuln-scan", osiLayers: ["L7"], tags: ["web", "vuln-scan", "commercial", "dast"] },
  { id: "acunetix", displayName: "Acunetix", binary: null, category: "web", riskTier: "active", notes: "Commercial scanner; requires Acunetix subscription and web UI or API.", phase: "vuln-scan", osiLayers: ["L7"], tags: ["web", "vuln-scan", "commercial", "dast"] },
  { id: "fiddler", displayName: "Fiddler", binary: null, category: "web", riskTier: "passive", notes: "GUI proxy/debugger; no standard CLI binary.", phase: "enum", osiLayers: ["L5", "L6", "L7"], tags: ["web", "proxy", "debug", "traffic"] },
  { id: "owasp-zap", displayName: "OWASP ZAP", binary: "zap.sh", category: "web", riskTier: "active", phase: "vuln-scan", osiLayers: ["L7"], tags: ["web", "vuln-scan", "proxy", "owasp"] },
  { id: "xsser", displayName: "XSSer", binary: "xsser", category: "web", riskTier: "active", phase: "vuln-scan", osiLayers: ["L7"], tags: ["web", "xss", "exploit"] },
  { id: "commix", displayName: "commix", binary: "commix", category: "web", riskTier: "controlled-exploit", phase: "exploit", osiLayers: ["L7"], tags: ["web", "command-injection", "exploit"] },
  { id: "arachni", displayName: "Arachni", binary: "arachni", category: "web", riskTier: "active", phase: "vuln-scan", osiLayers: ["L7"], tags: ["web", "vuln-scan", "crawl"] },
  { id: "secapps", displayName: "SecApps", binary: null, category: "web", riskTier: "active", notes: "Cloud-based security tools suite; browser/API access required.", phase: "vuln-scan", osiLayers: ["L7"], tags: ["web", "vuln-scan", "saas", "cloud"] },
  { id: "webreaver", displayName: "WebReaver", binary: null, category: "web", riskTier: "active", notes: "macOS GUI scanner; no CLI binary.", phase: "vuln-scan", osiLayers: ["L7"], tags: ["web", "vuln-scan", "macos"] },
  { id: "wpscan", displayName: "WPScan", binary: "wpscan", category: "web", riskTier: "active", phase: "vuln-scan", osiLayers: ["L7"], tags: ["web", "wordpress", "vuln-scan", "cms"] },
  { id: "ironwasp", displayName: "IronWASP", binary: null, category: "web", riskTier: "active", notes: "GUI scanner built on IronPython; no standard CLI binary.", phase: "vuln-scan", osiLayers: ["L7"], tags: ["web", "vuln-scan", "proxy"] },
  { id: "wordpress-exploit-framework", displayName: "WordPress Exploit Framework", binary: "wpxf", category: "web", riskTier: "controlled-exploit", phase: "exploit", osiLayers: ["L7"], tags: ["web", "wordpress", "exploit", "cms"] }
];
